// PROTOTYPE — initial storefront directions in one shareable, static concept.
const root = document.querySelector('#app');
const products = [
  ['Holiday Nostalgia', 'Coconut soy wax · 8 oz', 'yellow'],
  ['Cabin Fever', 'Coconut soy wax · 8 oz', 'sienna'],
  ['The Good Kind', 'Coconut soy wax · 8 oz', 'green'],
];
const candle = (name) => `<div class="candle"><div class="label"><small>Outsider Candle Co.</small><b>${name}</b><small>Coconut soy wax<br>Small batch</small></div></div>`;
const productCard = ([name, meta, color]) => `<button class="product" data-page="product"><div class="product-visual ${color}">${candle(name)}</div><h3>${name}</h3><p>${meta}</p></button>`;
const home = () => `<section class="hero"><div class="hero-copy"><p class="eyebrow">Outsider Candle Company</p><h1>Good candles for <em>real life.</em></h1><p>Thoughtfully poured, proudly made in Manitoba, and ready for whatever your day looks like.</p><button class="cta" data-page="shop">Shop candles</button></div><div class="hero-art">${candle('Holiday<br>Nostalgia')}</div></section><section class="section"><div class="section-head"><h2>Find your new<br>favourite scent.</h2><button class="text-link" data-page="shop">Shop all</button></div><div class="products">${products.map(productCard).join('')}</div></section><section class="proof"><div><strong>Small batch</strong><p>Poured with care</p></div><div><strong>Coconut soy</strong><p>For a clean, even burn</p></div><div><strong>Manitoba made</strong><p>Locally rooted</p></div></section>`;
const shop = () => `<section class="shop-header"><p class="eyebrow">The candle cupboard</p><h1 class="page-title">Smells like<br>something good.</h1><p>Small-batch candles with personality. Pick one for the moment, or give one to somebody who deserves a very good candle.</p></section><section class="shop-grid">${[...products, ['Prairie Rain','Coconut soy wax · 8 oz','green']].map(productCard).join('')}</section>`;
const product = () => `<section class="detail"><div class="detail-art">${candle('Holiday<br>Nostalgia')}</div><div class="detail-copy"><p class="eyebrow">Coconut soy wax candle</p><h1>Holiday<br>Nostalgia</h1><p class="price">$28.00</p><div class="details"><span>8 oz</span><span>40 hours</span><span>Small batch</span></div><p>For the long, good kind of holiday feeling. Warm, inviting, and a little bit familiar in the best possible way.</p><button class="cta">Add to bag</button></div></section>`;
const story = () => `<section class="story"><div class="story-art"><img src="/Users/kylesteele/Downloads/Exports/PNGs/Primary/OCC-Logos-FNL_OCC-Logo-Primary-White.png" alt="Outsider Candle Company"></div><div class="story-copy"><p class="eyebrow">Our story</p><p>Outsider is a family candle company built around the little rituals that make a day feel more like your own.</p><p>We make thoughtful, small-batch candles in Manitoba—designed to be lit often, gifted generously, and enjoyed without saving for a special occasion.</p></div></section>`;
const pages = { home, shop, product, story };
function render(page = location.hash.slice(1) || 'home') { if (!pages[page]) page = 'home'; location.hash = page; root.innerHTML = pages[page](); document.querySelectorAll('[data-page]').forEach(el => { if (el.dataset.page === page && el.closest('.prototype-bar')) el.classList.add('active'); el.addEventListener('click', () => render(el.dataset.page)); }); window.scrollTo({top:0, behavior:'smooth'}); }
window.addEventListener('hashchange', () => render(location.hash.slice(1)));
render();
